#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/downloads \
	/mnt/sabblob1 \
	/incomplete-downloads

#copy config
cp -rv /mnt/storage1/sabconfig/* /config

# permissions
chown -R abc:abc \
	/downloads \
	/incomplete-downloads \
	/config
